name: jetson
description: Object mapping and serialization core for JetLeaf â€” provides JSON, model binding, and conversion utilities.
version: 1.1.3

homepage: https://jetleaf.hapnium.com
repository: https://github.com/jetleaf/jetson
issue_tracker: https://github.com/jetleaf/jetson/issues
documentation: https://jetleaf.hapnium.com/docs/jetson

topics:
  - serialization
  - json
  - mapping
  - jetleaf
  - conversion

keywords:
  - jetleaf
  - jetson
  - serialization
  - json
  - mapper

environment:
  sdk: ^3.9.0

dependencies:
  meta: ^1.17.0
  jetleaf_lang: ^1.1.2
  jetleaf_convert: ^1.1.2
  jetleaf_pod: ^1.1.3
  jetleaf_utils: ^1.1.2
  jetleaf_core: ^1.1.4
  jetleaf_env: ^1.1.3

dev_dependencies:
  test: ^1.28.0
  lints: ^6.0.0